### ISSUE TITLE
[Bug]: granules_to_es fails for collections not configured for DAAC archival

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#446]
Environment: DEV and TEST with UDS v8.0.0

For collections not configured for DAAC archival (which is most), granules_to_es lambda fails which results in messages not clearing from granules_to_es_queue 

From cloudwatch logs

```
[ERROR] IndexError: list index out of range
Traceback (most recent call last):
  File "/var/task/cumulus_lambda_functions/granules_to_es/lambda_function.py", line 14, in lambda_handler
    GranulesIndexer(event).start()
  File "/var/task/cumulus_lambda_functions/granules_to_es/granules_indexer.py", line 111, in start
    daac_archiver.send_to_daac_internal(cnm_response)
  File "/var/task/cumulus_lambda_functions/daac_archiver/daac_archiver_logic.py", line 88, in send_to_daac_internal
    daac_config = daac_config[0]  # TODO This is currently not supporting more than 1 daac.

```
I suspect daac_config is never None but is an empty list if not configured for daac archival

https://github.com/unity-sds/unity-data-services/blob/develop/cumulus_lambda_functions/daac_archiver/daac_archiver_logic.py#L84-L88

**Comment by wphyojpl** [comment]
- Add DLQ
- fix the above error
