### ISSUE TITLE
[New Feature]: stage out should check for valid collection version in collection ID

### ISSUE THREAD

**Issue by ngachung** [unity-sds/unity-data-services#453]
Using collection ID without version will cause catalog to fail e.g.`"collection": "urn:nasa:unity:unity:dev:nga-unity-dev-output"`

`2024-10-29 21:07:30,287 [ERROR] [cumulus_lambda_functions.granules_cnm_ingester.granules_cnm_ingester_logic::154] missing collection. (failed to create): urn:nasa:unity:unity:dev:nga-unity-dev-output`

collection ID needs to include version e.g. `"collection": "urn:nasa:unity:unity:dev:nga-unity-dev-output___1"`

stage out should check that collection id stac items include version

**Comment by wphyojpl** [comment]
I think this is fixed via https://github.com/unity-sds/mdps-ds-lib/pull/61/files  and https://github.com/unity-sds/unity-data-services/pull/459/commits/a4c85dfd906850bc5bd8ff9623d122531ceaaf72

I remember having that issue when testing https://github.com/unity-sds/unity-data-services/issues/432

**Comment by ngachung** [comment]
Stage out works when providing collection without version and will default to version = 001. However, when calling unity_sds_client create_collection https://github.com/unity-sds/unity-monorepo/blob/main/libs/unity-py/unity_sds_client/services/data_service.py#L92, not providing version will cause the following error

```

[ERROR]	2025-01-09T01:22:02.469Z	0347861b-c15f-4780-b159-94f798310f93	error while creating new collection in Cumulus
Traceback (most recent call last):
  File "/var/task/cumulus_lambda_functions/uds_api/dapa/collections_dapa_creation.py", line 86, in create
    cumulus_collection_doc = collection_transformer.from_stac(self.__request_body)
  File "/var/task/mdps_ds_lib/lib/cumulus_stac/collection_transformer.py", line 491, in from_stac
    output_collection_cumulus['version'] = name_version[1]
IndexError: list index out of range
```


Maybe better documentation describing required format of collection ID (https://github.com/unity-sds/unity-monorepo/blob/main/libs/unity-py/unity_sds_client/resources/collection.py#L26) will be sufficient.
